apiVersion: v1
kind: Namespace
metadata:
  name: lego
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lego
  namespace: lego
data:
  lego.email: "dorks+fm@thisissoon.com"
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lego
  namespace: lego
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lego
    spec:
      containers:
      - name: lego
        image: jetstack/kube-lego:0.1.3
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: LEGO_EMAIL
          valueFrom:
            configMapKeyRef:
              name: lego
              key: lego.email
        - name: LEGO_URL
          valueFrom:
            configMapKeyRef:
              name: lego
              key: lego.url
        - name: LEGO_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: LEGO_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
