#
# Redis Kubernetes Service
#

# Persistent Volume Claim for Perisntent Redis Data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Service
# DNS = redis.redis
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
---
# Redis Replication Controller
apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        tier: backend
    spec:
      volumes:
      - name: redis-pv
        persistentVolumeClaim:
          claimName: redis-pvc
      containers:
      - name: redis
        image: redis:3.2.8-alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        volumeMounts:
          - mountPath: /data
            name: redis-pv
