apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  lego.email: "dorks+fm@thisissoon.com"
  # lego.url: "https://acme-staging.api.letsencrypt.org/directory"
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
